# -*- mode:org; mode:auto-fill; fill-column:80; coding:utf-8; -*-
* LibBERT --- a BERT (Binary ERlang Term) library for C++ and C.

BERT is a format for encoding binary data.  You can think of it as JSON for
binary formats.  BERT is based on [[http://www.erlang.org/doc/apps/erts/erl_ext_dist.html][Erlang's External Format]].

bert.h is the C API (you need to link =-lbert_capi=!).  bert.hpp is the C++ API
(header only).

See http://bert-rpc.org/

This library is written by Rüdiger Sonderfeld <[[ruediger@c-plusplus.de]]>.  Some
basic stuff (CMake setup etc.) is copied from the [[https://github.com/Flusspferd/flusspferd][Flusspferd project]].

Thanks to Nikolas Bowe, Samuel Chou, and Richard van der Hoff for their
contributions.

The library is licensed under the [[https://github.com/ruediger/Beerzlib-License][beerzlib license]].  The beerzlib license is a
modified zlib license.  It contains an additional clause that encourages users
to send beer (or other beverages or gifts) to the developers.  See the file
/license/ for the full text of the license.
